### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DWX12** [Darkhax-Minecraft/Resource-Hogs#1]
Tried starting the game and got this crash:

https://paste.dimdev.org/kasinaqaxo.mccrash

Interesting mod and I look forward to trying it out once more progress is made.

**Comment by Darkhax** [comment]
Thanks for checking out the mod, you need to install Bookshelf which is a dependency. Looks like I forgot to mark it as a dependency in curse, sorry about that.

**Comment by DWX12** [comment]
Ahh, not a problem. I'll add Bookshelf and will check out how well the mod works.

Thanks for getting back to me.
