### ISSUE TITLE
Soul Sand Hog Not Moving?

### ISSUE THREAD

**Issue by DeanAyalon** [Darkhax-Minecraft/Resource-Hogs#13]
I made a small pen with a soul-sand floor, so the resource hogs could dig truffles and farm soul sand
The problem is the pigs are not moving at all, and therefore not digging any new truffles, meaning I have to dig every single truffle before the hog will dig a new one
Is it because of the soul sand?
Is there any way to fix this?

**Comment by Darkhax** [comment]
Thanks for reporting this, it's a known issue with all resource hogs. They are very interested in the block below them and none of their AI will run once they're on a block they like.

**Comment by Darkhax** [comment]
This issue is fixed in https://github.com/Darkhax-Minecraft/Resource-Hogs/commit/c354ea447d51cd41cb7ad3fed04d83afa8a6061d

**Comment by DeanAyalon** [comment]
Nice! 👍 
To be honest, I’m way past finishing the game by now but it’s great hearing about bugs getting fixed and obstacles being overcome by developers :P
