### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by ReatExists** [Darkhax-Minecraft/Resource-Hogs#19]
Error: java.lang.NoClassDefFoundError: net/darkhax/resourcehogs/items/ItemPigSpawner
Here is the report
[crash-2020-07-24_21.03.58-client.txt](https://github.com/Darkhax-Minecraft/Resource-Hogs/files/4974727/crash-2020-07-24_21.03.58-client.txt)
Hope somebody could help!

**Comment by ReatExists** [comment]
Hello! I looked into it and found out the first issue was the same!

**Comment by ReatExists** [comment]
Everything is working so I dont need this anymore! Anyone who wanted to help thanks, but you did nothing. I am now gonna close this.

**Comment by Darkhax** [comment]
Your issue is that you didn't install the Bookshelf mod, it's listed as a dependency.
