### ISSUE TITLE
Only spawn egg in mod, which doesn't work.

### ISSUE THREAD

**Issue by DWX12** [Darkhax-Minecraft/Resource-Hogs#2]
Not exactly sure how much of the mod you have completed, but right now the only item showing up is a spawn egg, which doesn't spawn anything. The creative tab for the mod is also empty.

**Comment by Darkhax** [comment]
The mod is finished in terms of the features I have planned to implement. If there is only one spawn egg and it doesn't work, it's because you haven't configured any resource types. I guess I should add an error message to make that more obvious.

**Comment by DWX12** [comment]
Ohhhh, I wasn't aware I had to configure anything at first. Maybe I just expected the mod to come with some default settings. Knowing this, I would highly recommend setting up some defaults so that people can get a feel of how the mod works then go about tweaking it.

You mentioned a "truffle" on the main page, so that's what I was expecting. As an example, you could have the pig dig up brown mushrooms or maybe an iron ingot or nugget. That should eliminate this problem. In any case, that's good information to know.

**Comment by Darkhax** [comment]
This issue has been addressed by throwing an error message into the chat if the mod has not been configured, similar to the other errors displayed by this mod.
