### ISSUE TITLE
Astral Sorcery Bootes Ritual Does Not Cause Bacon to Drop

### ISSUE THREAD

**Issue by whatamike** [Darkhax-Minecraft/Resource-Hogs#20]
When Resource Hogs are affected with the Astral Sorcery Ritual of Bootes, pork chops are the only dropped item.

Steps to reproduce:

1. Spawn any Resource Hog
2. Create Ritual of Bootes
3. Ensure Hogs are in ritual radius

Expected Behavior:

- A random mixture of pork chops and Resource Hogs bacon is spawned

Actual Behavior:

- Only pork chops are spawned

Astral Sorcery Loot Selection: https://github.com/HellFirePvP/AstralSorcery/blob/e8434f1a09356632babefee1925626dc3deefb2a/src/main/java/hellfirepvp/astralsorcery/common/util/entity/EntityUtils.java#L216

Modpack: SkyFactory 4
Version: 4.2.2
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2854
Astral Sorcery Version: 1.10.24
Resource Hogs Version: 1.0.14

**Comment by Darkhax** [comment]
The mods generate loot in an incompatible way. Astral Sorcery is generating loot at a lower level in the process so my nbt-dependent loot is not included. They could fix this, and simplify their code by just doing entity#dropLoot or I could rewrite this mod to add the loot earlier in the chain. Unfortunately this mod is 3 years old and I have no plans to update it at this time. I would suspect the Astral team feel similar about supporting older versions on their end too.
