### ISSUE TITLE
[Suggestion] Mod compatability/integration with Biomes O Plenty

### ISSUE THREAD

**Issue by DWX12** [Darkhax-Minecraft/Resource-Hogs#3]
Since players need to use a bucket of mud to make a hog, it would be a good idea to incorporate mud from Biomes O Plenty. BOP only has mud blocks and brick items (in addition to building blocks of mud) and the only liquid BOP has that's close, is quick sand.

If the mod detects BOP, it could switch recipes to using an empty bucket and a block or mud or a water bucket and a block of mud instead of the standard recipe. There should also be an option to use the original recipe in the config.

There might be other mods that have mud, but, aside from BOP, I'm not sure. If I come across any more, I'll be sure to let you know.

**Comment by Darkhax** [comment]
The mud in this mod isn't generic mud, it's a special mud item that is crafted. If modpack authors want to change the recipe, or add different recipes they can do so using CraftTweaker.
