### ISSUE TITLE
[Suggestion] Allow breeding resource hogs

### ISSUE THREAD

**Issue by ComplainingSkelzie** [Darkhax-Minecraft/Resource-Hogs#4]
It would be nice to be able to farm resources by breeding hogs and then killing adults, similar to a vanilla pork farm. It could be a config setting that's off by default. If you want to go the extra mile, you could also allow user-defined hybrids, so that it would be possible to set up something like cobalt hog + ardite hog = manyullyn hog.

**Comment by Darkhax** [comment]
You can already breed resource hogs together. There is a 50% chance that it will be a vanilla pig. A 25% chance that it will be the same type as the first parent, and a 25% chance that it will be the same type as the second parent. Allowing variants to blend together could be cool but this mod was made specifically for Sky Factory 4, and they specifically did not want that feature. I can still add it as a configurable thing but I don't know if/when I will have time to add it.

**Comment by DWX12** [comment]
More or less it would become the pig equivalent of the cow mod that's out there that allows the farming of cows for resources. I agree in both respects, a config option for those that want it, but I think it's cool to have an alternative to just another mob farm (which sounds like another mods name).

**Comment by ComplainingSkelzie** [comment]
Ah, ok. I jumped to conclusions after seeing 3 different breeding attempts give vanilla pigs. Having configurable hybrids would be nice, but it's understandable if it never gets added. As for existing mods, pigs as-is seem a lot like weaker and simpler chickens, in that they create the resources in-world given enough time. Cows typically give fluids when milked rather than being farmed like meat animals, so I thought it would be nice to add a third type of animal-based resource farm to the mix.

**Comment by jelaw21** [comment]
I second the option to have a mixed breeding config option. On the one hand, I like the additional challenge of filtering out the normal pigs to increase resource production, but on the other hand, its much slower than others. I can see where both may have merits in a pack.

Just to be clear, the config would be a boolean on whether resource hogs have a chance to breed regular vanilla pigs?

**Comment by Darkhax** [comment]
After thinking about this feature request it would be a lot of work to create a new system for this and it would go against the goal of the original mod. It's not meant to be a whole sale clone of the similar resource mob mods.
