### ISSUE TITLE
Allow OreDictionary Resources to Cycle Through on Recipe Page

### ISSUE THREAD

**Issue by Darkosto** [Darkhax-Minecraft/Resource-Hogs#7]
Currently, if the resource has multiple oredict entries it shows a recipe per item instead of cycling through. After a certain number of pigs, the page count gets to be a bit high and may be cumbersome for the users to look through.

**Comment by Darkhax** [comment]
From what I can see, and have found in testing, this is more so a limitation of JEI. The items have the same item and meta, but different NBT, so it's seeing them all as the same item. I've sent mezz a message about this, but I doubt this can be easily fixed.
